services:
  - type: web
    name: routemind-backend
    env: python
    plan: free
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: routemind-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "routemind-backend.onrender.com" # Change this after your first deploy

databases:
  - name: routemind-db
    plan: free
